sudo: required

language: generic

services:
    - docker

before_install:
    - docker build  -t krishnamaheshteja/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true krishnamaheshteja/docker-react npm run test